name: check for new releases of upstream data
on:
    workflow_dispatch:

jobs:
  build:
    name: RedisTimeSeries
    runs-on: ubuntu-latest
    steps:
      - id: timezone_db
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            repository: evansiroky/timezone-boundary-builder
       
      - uses: actions/checkout@v4
      - name: create an issue
        if: ${{ steps.timezone_db.outputs.release != '42' }}
        uses: dacbd/create-issue-action@main
        with:
           token: ${{ github.token }}
           title: Simple test issue
           body: my new issue
